"""Subprocess-isolated attach API for Jaxley backends.

Provides attach() — build your Jaxley model normally, attach CompNeuroVis
visualization without subclassing JaxleyBackend.

Usage::

    import jaxley as jx
    from jaxley.channels import HH
    from compneurovis.backends.jaxley.attach import attach

    cell = jx.Cell()
    cell.insert(HH())

    def setup(network, cells):
        network.stimulate(jx.step_current(0.0, 10.0, 0.1, dt=0.025, t_max=100.0))

    app = attach(cells=[cell], setup=setup)
    app.show(title="HH Jaxley")

No subclassing. Subprocess isolation handled automatically.
Jaxley/JAX runs in the backend subprocess; Qt frontend stays in the main process.
"""
from __future__ import annotations

import inspect
import multiprocessing as mp
import runpy
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable, Sequence

from compneurovis.backends.host import BackendHost
from compneurovis.backends.jaxley.backend import JaxleyBackend
from compneurovis.core.controls import ActionSpec, ControlSpec, ScalarValueSpec
from compneurovis.core.hosts import configure_multiprocessing
from compneurovis.core.messages import InvokeAction, SetControl
from compneurovis.core.runtime import AppRuntime
from compneurovis.transports.pipe import PipeEndpoint, make_pipe_pair

# ---------------------------------------------------------------------------
# Module-level endpoint flag — set by _attach_script_worker before re-run
# ---------------------------------------------------------------------------

_attach_endpoint: PipeEndpoint | None = None


def _attach_script_worker(script_path: str, endpoint: PipeEndpoint) -> None:
    """Entry point for the backend subprocess.

    Must be top-level in this module so multiprocessing can pickle it by
    qualified name (compneurovis.backends.jaxley.attach._attach_script_worker).
    Do not move or rename.
    """
    global _attach_endpoint
    _attach_endpoint = endpoint
    runpy.run_path(script_path, run_name="__main__")


# ---------------------------------------------------------------------------
# Binding descriptors
# ---------------------------------------------------------------------------

@dataclass
class _ControlBinding:
    name: str
    label: str
    get: Callable[[], float]
    set: Callable[[Any], None]
    min: float = 0.0
    max: float = 1.0
    refresh_externals: bool = False
    refresh_params: bool = False
    _control_id: str = field(init=False, default="")

    def _register(self, index: int) -> None:
        self._control_id = f"ctrl_{index}_{self.name}"

    def _control_spec(self) -> ControlSpec:
        return ControlSpec(
            id=self._control_id,
            label=self.label,
            value_spec=ScalarValueSpec(default=self.get(), min=self.min, max=self.max),
            send_to_backend=True,
        )


@dataclass
class _ActionBinding:
    name: str
    label: str
    fn: Callable[[], None]
    _action_id: str = field(init=False, default="")

    def _register(self, index: int) -> None:
        self._action_id = f"action_{index}_{self.name}"

    def _action_spec(self) -> ActionSpec:
        return ActionSpec(id=self._action_id, label=self.label)


# ---------------------------------------------------------------------------
# _AttachBackend — JaxleyBackend subclass generated by JaxleyAttachAdapter
# ---------------------------------------------------------------------------

class _AttachBackend(JaxleyBackend):
    def __init__(
        self,
        *,
        cells: list,
        setup_fn: Callable | None,
        controls: list[_ControlBinding],
        actions: list[_ActionBinding],
        dt: float,
        v_init: float,
        title: str,
        **kwargs,
    ) -> None:
        super().__init__(dt=dt, v_init=v_init, title=title, **kwargs)
        self._provided_cells = cells
        self._setup_fn = setup_fn
        self._provided_controls = controls
        self._provided_actions = actions

    def build_cells(self) -> Iterable:
        return self._provided_cells

    def setup_model(self, network, cells):
        if self._setup_fn is not None:
            self._setup_fn(network, cells)

    def control_specs(self) -> dict[str, ControlSpec]:
        return {c._control_id: c._control_spec() for c in self._provided_controls}

    def action_specs(self) -> dict[str, ActionSpec]:
        return {a._action_id: a._action_spec() for a in self._provided_actions}

    def apply_control(self, control_id: str, value: Any) -> bool:
        for c in self._provided_controls:
            if c._control_id == control_id:
                c.set(float(value))
                if c.refresh_externals:
                    self.refresh_runtime_externals()
                    self._step_index = 0
                if c.refresh_params:
                    self.refresh_runtime_parameters(preserve_state=True)
                return True
        return False

    def on_action(self, action_id: str, payload: dict, context: Any) -> bool:
        for a in self._provided_actions:
            if a._action_id == action_id:
                a.fn()
                return True
        return False


# ---------------------------------------------------------------------------
# JaxleyAttachAdapter — accumulates bindings, orchestrates show()
# ---------------------------------------------------------------------------

class JaxleyAttachAdapter:
    def __init__(
        self,
        *,
        cells: list,
        setup: Callable | None,
        dt: float,
        v_init: float,
        backend_kwargs: dict,
    ) -> None:
        self._cells = cells
        self._setup_fn = setup
        self._dt = dt
        self._v_init = v_init
        self._backend_kwargs = backend_kwargs
        self._controls: list[_ControlBinding] = []
        self._actions: list[_ActionBinding] = []

    def control(
        self,
        name: str,
        *,
        label: str,
        get: Callable[[], float],
        set: Callable[[Any], None],
        min: float = 0.0,
        max: float = 1.0,
        refresh_externals: bool = False,
        refresh_params: bool = False,
    ) -> "JaxleyAttachAdapter":
        b = _ControlBinding(
            name=name, label=label, get=get, set=set, min=min, max=max,
            refresh_externals=refresh_externals, refresh_params=refresh_params,
        )
        b._register(len(self._controls))
        self._controls.append(b)
        return self

    def action(
        self,
        name: str,
        *,
        label: str,
        fn: Callable[[], None],
    ) -> "JaxleyAttachAdapter":
        b = _ActionBinding(name=name, label=label, fn=fn)
        b._register(len(self._actions))
        self._actions.append(b)
        return self

    def _make_backend(self, title: str) -> _AttachBackend:
        return _AttachBackend(
            cells=self._cells,
            setup_fn=self._setup_fn,
            controls=self._controls,
            actions=self._actions,
            dt=self._dt,
            v_init=self._v_init,
            title=title,
            **self._backend_kwargs,
        )

    def show(self, *, title: str = "CompNeuroVis") -> None:
        if _attach_endpoint is not None:
            # Subprocess: build AppSpec from fresh Jaxley state, run as backend actor.
            backend = self._make_backend(title)
            app_spec = backend.build_startup_app_spec()
            host = BackendHost(endpoint=_attach_endpoint)
            host.start(lambda: backend, app_spec)
            try:
                while not host.should_stop():
                    started = time.monotonic()
                    host.step()
                    remaining = host.idle_sleep() - (time.monotonic() - started)
                    if remaining > 0:
                        time.sleep(remaining)
            except (BrokenPipeError, OSError):
                pass
            finally:
                host.stop()

        elif mp.current_process().name == "MainProcess":
            # Main process: build AppSpec from existing Jaxley state, spawn backend
            # subprocess, run Qt frontend.
            from compneurovis.frontends.vispy.frontend import VispyFrontendWindow
            from compneurovis.frontends.vispy.host import VispyFrontendHost

            backend = self._make_backend(title)
            app_spec = backend.build_startup_app_spec()

            script_path = inspect.stack()[-1].filename
            pair = make_pipe_pair(left_name="frontend", right_name="backend")
            configure_multiprocessing()

            backend_process = mp.Process(
                target=_attach_script_worker,
                args=(script_path, pair.right),
            )
            backend_process.start()
            pair.right.close()

            runtime = AppRuntime(app_spec=app_spec)
            frontend_host = VispyFrontendHost(
                actor_source=VispyFrontendWindow,
                runtime=runtime,
                endpoint=pair.left,
            )
            frontend_host.start()
            frontend_host.run()
            frontend_host.stop()

            backend_process.join(timeout=2)
            if backend_process.is_alive():
                backend_process.terminate()
                backend_process.join()
        # else: subprocess bootstrap re-import (Windows spawn fixup_main) — do nothing


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def attach(
    *,
    cells: Sequence,
    setup: Callable | None = None,
    dt: float = 0.025,
    v_init: float = -70.0,
    **kwargs,
) -> JaxleyAttachAdapter:
    """Attach CompNeuroVis to an existing Jaxley model.

    Args:
        cells:  Jaxley Cell objects that define the morphology.
        setup:  Optional callable(network, cells) called during model setup.
                Use to add stimuli or configure the network before JAX tracing.
                Recordings are managed automatically.
        dt:     Simulation timestep in ms. Defaults to 0.025.
        v_init: Initial membrane voltage (mV). Defaults to -70.0.
        **kwargs: Forwarded to JaxleyBackend (e.g. max_samples, display_dt).

    Returns a JaxleyAttachAdapter. Call .control() / .action() to add
    bindings, then .show() to launch.
    """
    return JaxleyAttachAdapter(
        cells=list(cells),
        setup=setup,
        dt=dt,
        v_init=v_init,
        backend_kwargs=kwargs,
    )


__all__ = ["attach", "JaxleyAttachAdapter"]
