"""Subprocess-isolated attach API for NEURON backends.

Provides attach() — build your NEURON model normally, attach CompNeuroVis
visualization without subclassing NeuronBackend.

Usage::

    from neuron import h
    from compneurovis.backends.neuron.attach import attach

    soma = h.Section(name="soma")
    soma.insert("hh")
    stim = h.IClamp(soma(0.5))
    h.dt = 0.025
    h.finitialize(-65.0)

    app = attach(sections=[soma])
    app.control("IClamp (nA)",
                get=lambda: float(stim.amp),
                set=lambda v: setattr(stim, "amp", float(v)),
                min=-0.2, max=0.5)
    app.show(title="HH")

No subclassing. No RunSpec. Subprocess isolation handled automatically.
NEURON runs in the backend subprocess; Qt frontend stays in the main process.
"""
from __future__ import annotations

import inspect
import multiprocessing as mp
import runpy
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Sequence

import numpy as np

from compneurovis.backends.host import BackendHost
from compneurovis.backends.neuron.backend import NeuronBackend
from compneurovis.core.controls import ActionSpec, ControlSpec, ScalarValueSpec
from compneurovis.core.hosts import configure_multiprocessing
from compneurovis.core.messages import InvokeAction, SetControl
from compneurovis.core.runtime import AppRuntime
from compneurovis.transports.pipe import PipeEndpoint, make_pipe_pair

# ---------------------------------------------------------------------------
# Module-level endpoint flag — set by _attach_script_worker before re-run
# ---------------------------------------------------------------------------

_attach_endpoint: PipeEndpoint | None = None


def _attach_script_worker(script_path: str, endpoint: PipeEndpoint) -> None:
    """Entry point for the backend subprocess.

    Must be top-level in this module so multiprocessing can pickle it by
    qualified name (compneurovis.backends.neuron.attach._attach_script_worker).
    Do not move or rename.
    """
    global _attach_endpoint
    _attach_endpoint = endpoint
    runpy.run_path(script_path, run_name="__main__")


# ---------------------------------------------------------------------------
# Binding descriptors
# ---------------------------------------------------------------------------

@dataclass
class _ControlBinding:
    name: str
    label: str
    get: Callable[[], float]
    set: Callable[[Any], None]
    min: float = 0.0
    max: float = 1.0
    _control_id: str = field(init=False, default="")

    def _register(self, index: int) -> None:
        self._control_id = f"ctrl_{index}_{self.name}"

    def _control_spec(self) -> ControlSpec:
        return ControlSpec(
            id=self._control_id,
            label=self.label,
            value_spec=ScalarValueSpec(default=self.get(), min=self.min, max=self.max),
            send_to_backend=True,
        )


@dataclass
class _ActionBinding:
    name: str
    label: str
    fn: Callable[[], None]
    _action_id: str = field(init=False, default="")

    def _register(self, index: int) -> None:
        self._action_id = f"action_{index}_{self.name}"

    def _action_spec(self) -> ActionSpec:
        return ActionSpec(id=self._action_id, label=self.label)


# ---------------------------------------------------------------------------
# _AttachBackend — NeuronBackend subclass generated by NeuronAttachAdapter
# ---------------------------------------------------------------------------

class _AttachBackend(NeuronBackend):
    def __init__(
        self,
        *,
        sections: list,
        controls: list[_ControlBinding],
        actions: list[_ActionBinding],
        step_fn: Callable[[], None] | None,
        dt: float,
        v_init: float,
        title: str,
    ) -> None:
        super().__init__(dt=dt, v_init=v_init, title=title)
        self._provided_sections = sections
        self._provided_controls = controls
        self._provided_actions = actions
        self._custom_step_fn = step_fn

    def build_sections(self) -> list:
        return self._provided_sections

    def control_specs(self) -> dict[str, ControlSpec]:
        return {c._control_id: c._control_spec() for c in self._provided_controls}

    def action_specs(self) -> dict[str, ActionSpec]:
        return {a._action_id: a._action_spec() for a in self._provided_actions}

    def apply_control(self, control_id: str, value: Any) -> bool:
        for c in self._provided_controls:
            if c._control_id == control_id:
                c.set(float(value))
                return True
        return super().apply_control(control_id, value)

    def on_action(self, action_id: str, payload: dict, context: Any) -> bool:
        for a in self._provided_actions:
            if a._action_id == action_id:
                a.fn()
                return True
        return False

    def advance(self) -> None:
        if self._custom_step_fn is None:
            super().advance()
            return
        from neuron import h
        t_target = float(h.t) + self.sim_ms_per_frame()
        steps = []
        times = []
        while True:
            self._custom_step_fn()
            times.append(float(h.t))
            steps.append(self._sample_step())
            if float(h.t) >= t_target:
                break
        self._emit_batch(np.asarray(times, dtype=np.float32), steps)

    def idle_sleep(self) -> float:
        return 1.0 / 60.0


# ---------------------------------------------------------------------------
# NeuronAttachAdapter — accumulates bindings, orchestrates show()
# ---------------------------------------------------------------------------

class NeuronAttachAdapter:
    def __init__(
        self,
        *,
        sections: list,
        step: Callable[[], None] | None,
        dt: float,
        v_init: float,
    ) -> None:
        self._sections = sections
        self._step_fn = step
        self._dt = dt
        self._v_init = v_init
        self._controls: list[_ControlBinding] = []
        self._actions: list[_ActionBinding] = []

    def control(
        self,
        name: str,
        *,
        label: str,
        get: Callable[[], float],
        set: Callable[[Any], None],
        min: float = 0.0,
        max: float = 1.0,
    ) -> "NeuronAttachAdapter":
        b = _ControlBinding(name=name, label=label, get=get, set=set, min=min, max=max)
        b._register(len(self._controls))
        self._controls.append(b)
        return self

    def action(
        self,
        name: str,
        *,
        label: str,
        fn: Callable[[], None],
    ) -> "NeuronAttachAdapter":
        b = _ActionBinding(name=name, label=label, fn=fn)
        b._register(len(self._actions))
        self._actions.append(b)
        return self

    def _make_backend(self, title: str) -> _AttachBackend:
        return _AttachBackend(
            sections=self._sections,
            controls=self._controls,
            actions=self._actions,
            step_fn=self._step_fn,
            dt=self._dt,
            v_init=self._v_init,
            title=title,
        )

    def show(self, *, title: str = "CompNeuroVis") -> None:
        if _attach_endpoint is not None:
            # Subprocess: build AppSpec from fresh NEURON state, run as backend actor.
            backend = self._make_backend(title)
            app_spec = backend.build_startup_app_spec()
            host = BackendHost(endpoint=_attach_endpoint)
            host.start(lambda: backend, app_spec)
            try:
                while not host.should_stop():
                    started = time.monotonic()
                    host.step()
                    remaining = host.idle_sleep() - (time.monotonic() - started)
                    if remaining > 0:
                        time.sleep(remaining)
            except (BrokenPipeError, OSError):
                pass
            finally:
                host.stop()

        elif mp.current_process().name == "MainProcess":
            # Main process: build AppSpec from existing NEURON state, spawn backend
            # subprocess, run Qt frontend.
            from compneurovis.frontends.vispy.frontend import VispyFrontendWindow
            from compneurovis.frontends.vispy.host import VispyFrontendHost

            backend = self._make_backend(title)
            app_spec = backend.build_startup_app_spec()

            script_path = inspect.stack()[-1].filename
            pair = make_pipe_pair(left_name="frontend", right_name="backend")
            configure_multiprocessing()

            backend_process = mp.Process(
                target=_attach_script_worker,
                args=(script_path, pair.right),
            )
            backend_process.start()
            pair.right.close()

            runtime = AppRuntime(app_spec=app_spec)
            frontend_host = VispyFrontendHost(
                actor_source=VispyFrontendWindow,
                runtime=runtime,
                endpoint=pair.left,
            )
            frontend_host.start()
            frontend_host.run()
            frontend_host.stop()

            backend_process.join(timeout=2)
            if backend_process.is_alive():
                backend_process.terminate()
                backend_process.join()
        # else: subprocess bootstrap re-import (Windows spawn fixup_main) — do nothing


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def attach(
    *,
    sections: Sequence,
    step: Callable[[], None] | None = None,
    dt: float | None = None,
    v_init: float = -65.0,
) -> NeuronAttachAdapter:
    """Attach CompNeuroVis to an existing NEURON model.

    Args:
        sections: NEURON section objects that define the morphology.
        step:     Optional custom step function called instead of h.fadvance().
                  Defaults to h.fadvance() if None.
        dt:       Simulation timestep in ms. Defaults to h.dt at call time.
        v_init:   Initial membrane voltage (mV). Defaults to -65.0.

    Returns a NeuronAttachAdapter. Call .control() / .action() to add
    bindings, then .show() to launch.
    """
    from neuron import h
    resolved_dt = float(dt) if dt is not None else float(h.dt)
    return NeuronAttachAdapter(
        sections=list(sections),
        step=step,
        dt=resolved_dt,
        v_init=v_init,
    )


__all__ = ["attach", "NeuronAttachAdapter"]
